apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: jcdigital-uk-tls
spec:
  secretName: jcdigital-uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jcdigital.uk
  dnsNames:
    - jcdigital.uk
    - www.jcdigital.uk
